[licenses]
allow = [
  # permissive licenses
  "0BSD",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "Unicode-DFS-2016",
  "Unlicense",
  "Zlib",
  # permissive license with unclear patent grant
  "CC0-1.0",
  # weak/limited copyleft licenses
  "MPL-2.0",
  "OpenSSL", # https://en.wikipedia.org/wiki/OpenSSL#Licensing
]

# Clearify licence: https://github.com/briansmith/ring/issues/902
# Plan to remove OpenSSL: https://github.com/briansmith/ring/issues/1827
[[licenses.clarify]]
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[advisories]
yanked = "warn"
ignore = [
  # phyllo unmaintained: https://github.com/wanderers-nft/phyllo
  "RUSTSEC-2024-0336",
  "RUSTSEC-2023-0065"
]

[bans]
multiple-versions = "allow"
